linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - gofumpt
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  lll:
    line-length: 160